spring:
   datasource:
      url: jdbc:mysql://localhost:3306/liquibase_test?useSSL=false
      username: root
      password: P@ssw0rd
      
   jpa:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto: none
   
   liquibase:
      change-log: classpath:db/liquibase-changelog.yml
server:
   servlet:
      context-path: /liquibase-test